export const IGNORED_DIRECTORY_NAMES = new Set([
  ".git",
  ".next",
  "node_modules",
  "dist",
  "build",
  "coverage",
  ".turbo",
  ".cache",
]);

export const NAVIGATION_ONLY_FILENAMES = new Set([
  "README.md",
  "INDEX.md",
  "CHANGELOG.md",
  "FOUNDATION_MAP.md",
  "PROJECT_STRUCTURE.md",
]);

export const EXCLUDED_ARTIFACT_STATUSES = new Set([
  "deprecated",
  "obsolete",
  "superseded",
  "rejected",
]);

export const PREFERRED_ARTIFACT_STATUSES = new Set([
  "accepted",
  "approved",
  "active",
]);

export const DOCUMENT_ID_PATTERN =
  /\b(ADR|ENG|PK|OPS|KA|DDS|ADV)-\d{4}\b/gi;

export const FAMILY_KEYWORDS: Record<string, readonly string[]> = {
  Foundation: ["foundation", "vision", "manifesto", "premise", "theory of change"],
  PK: ["product", "principle", "capability", "mvp"],
  ADR: ["architecture decision", "adr", "decision record"],
  ENG: ["engineering", "specification", "eng-"],
  KA: ["knowledge architecture", "pkos architecture"],
  OPS: ["operations", "deployment", "runbook", "aws"],
  DDS: ["detailed design", "dds"],
  ADV: ["advisor", "adv-"],
};

export const STOP_WORDS = new Set([
  "a",
  "an",
  "the",
  "and",
  "or",
  "but",
  "for",
  "with",
  "from",
  "that",
  "this",
  "what",
  "which",
  "who",
  "why",
  "how",
  "when",
  "where",
  "must",
  "should",
  "would",
  "could",
  "can",
  "will",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "have",
  "has",
  "had",
  "do",
  "does",
  "did",
  "to",
  "of",
  "in",
  "on",
  "at",
  "by",
  "as",
  "it",
  "its",
  "not",
  "no",
  "all",
  "any",
  "our",
  "your",
  "their",
  "de",
  "da",
  "do",
  "dos",
  "das",
  "e",
  "o",
  "a",
  "os",
  "as",
  "um",
  "uma",
  "uns",
  "umas",
  "para",
  "por",
  "com",
  "sem",
  "sobre",
  "que",
  "qual",
  "quais",
  "como",
  "quando",
  "onde",
  "porque",
  "porquê",
  "não",
  "nao",
  "sim",
  "este",
  "esta",
  "esse",
  "essa",
  "isso",
  "aquilo",
  "prodignus",
  "decision",
  "council",
  "canonical",
  "executive",
  "summarize",
  "summary",
]);
